import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar is derived from the `docs/` tree. Add, remove, or rename `.md`
 * files and folders; nested folders become categories.
 *
 * Order: `sidebar_position` in front matter, else `_category_.json`
 * `position`, else alphabetical. See:
 * https://docusaurus.io/docs/sidebar/autogenerated
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
