import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Docusaurus will auto-generate sidebar from filesystem
  // (one big tree under /projects). You can split by folders later if you like.
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;